import { IResolvedEngineConfiguration } from '~/configuration/types';
import { IEventbus } from '~/eventbus/types';
import { TResultCallback } from '~/types';
import { ITimelineProvider } from './types';
export declare class RequestAnimationFrameTimelineProvider implements ITimelineProvider {
    private eventbus;
    private config;
    private _requestID;
    private _last;
    private _currentPosition;
    private _updateBound;
    private _eventbusListeners;
    private _firstFrame;
    private _currentPlaylistItem;
    private _granularity;
    private _playState;
    private _playlist;
    private _containerElement;
    loop: boolean;
    constructor(eventbus: IEventbus, config: IResolvedEngineConfiguration);
    private _extractPlaylist;
    playlistItem(uri: string): void;
    private _addEventListeners;
    private _update;
    private _start;
    private _reset;
    private _resize;
    private _container;
    private _cancelAnimationFrame;
    init(): Promise<any>;
    destroy(): void;
    toggleplay(): void;
    start(): void;
    stop(): void;
    pause(): void;
    seek(position: number): void;
    getPosition(): number;
    getDuration(): number;
    requestDurationHandler(callBack: TResultCallback): void;
}
