import 'mediaelement';
import { IResolvedEngineConfiguration } from '../configuration/types';
import { IEventbus } from '../eventbus/types';
import { TResultCallback } from '../types';
import { ITimelineProvider } from './types';
export declare class MediaElementTimelineProvider implements ITimelineProvider {
    private eventbus;
    private config;
    private _videoElementId;
    private _eventbusListeners;
    private _playlist;
    private _length;
    private _urls;
    player: mediaelementjs.MediaElementPlayer | undefined;
    loop: boolean;
    constructor(eventbus: IEventbus, config: IResolvedEngineConfiguration);
    _addEventListeners(): void;
    _extractUrls(configuration: IResolvedEngineConfiguration): string[];
    init(): Promise<unknown>;
    private _timeUpdateHandler;
    private _addVideoElements;
    _extractFileType(url: string): string;
    playlistItem(uri: string): void;
    start(): void;
    stop(): void;
    destroy(): void;
    pause(): void;
    seek(position: number): void;
    resize(): void;
    duration(resultCallback: TResultCallback): void;
    getDuration(): number;
    getPosition(): number;
    _container(resultCallback: TResultCallback): void;
}
