name: CI
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/ci-build.yml
